### PR TITLE
RTL Hebrew titles

### PR DESCRIPTION
**Pull request by sijad**
it looks better with new RTL changes

### CODE REVIEW

**Comment by mikemcquaid** [comment]
This needs rebased on `master` or recreated, sorry 😭

**Comment by sijad** [comment]
done, @mikemcquaid thanks a lot
I'm sorry for this lot of issues and PR's opening

**Comment by sijad** [comment]
can you please wait a little longer?

**Comment by sijad** [comment]
it good to go

**Comment by mikemcquaid** [comment]
> I'm sorry for this lot of issues and PR's opening

Don't apologise, that's a good rather than bad thing! Thanks again @sijad!

**Pull request merged**
