### PR TITLE
"What Does Homebrew Do?" now in Spanish

### PR DESCRIPTION
**Pull request by joelwallis**
Now in Spanish, the most important language for translations (considering that English is not a translation but the default text).

Also, should I open a PR for every language or just submit all of them in one bundled PR?

### CODE REVIEW

**Comment by mikemcquaid** [comment]
@joelwallis Feel free to submit them all in this PR!

**Comment by xu-cheng** [comment]
@mikemcquaid  Any reason that Travis CI is not working?

**Comment by mikemcquaid** [comment]
@xu-cheng Don't know, sorry.

**Comment by mikemcquaid** [comment]
@xu-cheng I've reenabled it now.

**Comment by mikemcquaid** [comment]
Merging for now, thanks!

**Pull request merged**
