### PR TITLE
use https://git.io/brew-docs/ to redirect document.

### PR DESCRIPTION
**Pull request by xu-cheng**
* Create the webpage http://brew.sh/doc/ which will redirect to https://github.com/Homebrew/homebrew/tree/master/share/doc/homebrew#readme.
* Use http://brew.sh/doc/ to short document url.

### CODE REVIEW

**Comment by mikemcquaid** [comment]
Instead of the redirect lets use http://git.io/brew-docs instead.

**Comment by xu-cheng** [comment]
I don't think http://git.io/brew-docs is a good idea. As it's hard linked to https://github.com/Homebrew/homebrew/tree/master/share/doc/homebrew#readme. If by any chance in the future, we want to move the documents somewhere else(I know it's slightly in foreseeable future), we would have to change the link again. On the contrary, using http://brew.sh/doc/ a webpage we can control, we can redirect it to anywhere if we want.

**Comment by mikemcquaid** [comment]
I don't really like making technical decisions based on speculative unknown future decisions. Again, I don't think that's solving a problem users are experiencing. We can add a new git.io link if we want in future or I can change it. The Jekyll redirects are a bad hack and nasty user experience.

**Comment by xu-cheng** [comment]
Isn't http://git.io/brew-docs also a redirect?

>  I can change it

Really? sweet power. :heart_eyes: 

OK, I will change into http://git.io/brew-docs.

**Comment by mikemcquaid** [comment]
It's a 301 redirect rather than a HTML one. With the latter some people in some browsers will see a flickering as the other page briefly loads.

**Comment by xu-cheng** [comment]
Updated.

**Comment by xu-cheng** [comment]
@mikemcquaid I wonder can we use the same tech to short the install url.

**Comment by mikemcquaid** [comment]
@xu-cheng Probably not; you need to pass an additional argument to e.g. `curl` to get it to follow redirects.

**Comment by xu-cheng** [comment]
@mikemcquaid I know that part. And we have the argument (`-L`) in curl command. 

The reason I don't think it's a good idea using `git.io` is I thought we cannot control it (for example relocate it) after creating the link.

**Pull request merged**
