### PR TITLE
General cleanup and updates

### PR DESCRIPTION
**Pull request by MikeMcQuaid**
- Gemfile: update all gems to their latest versions
- Cleanup configuration and enable default GitHub Pages plugins
- Add support for blog posts at a future date

### CODE REVIEW

**Comment by zmwangx** [comment]
Currently there doesn't seem to be any link to blog posts or `/atom.xml` on the home page.

**Comment by MikeMcQuaid** [comment]
@zmwangx Yep, that's intentional as there aren't any posts yet so we don't want to advertise the Atom feed or posts.

**Comment by zmwangx** [comment]
Oh I see, I thought you were going to hold off merging until having a post.

**Comment by MikeMcQuaid** [comment]
Nah. Want to just split up this stuff into a few pieces so it's easier to test/review.

**Pull request merged**
