### PR TITLE
Contrast for links and links-vs-body text

### PR DESCRIPTION
**Pull request by matatk**
This follows on from the discussion in https://github.com/Homebrew/homebrew.github.io/issues/154

I have been using http://jxnblk.com/colorable/demos/matrix/ to tweak the colours of:

 * the page background;
 * body text and
 * link text

so that they are, hopefully, easier to read - particularly so that links are more distinguishable from the body text.  Here is my first effort at this.

Here are the original colours and contrast ratios:
homebrew-original
Of note:
 * Link text to page background is 4.33:1
 * Link text to body text is only 2.27:1

Here are the ones I currently have:
homebrew-proposed
Of note:
 * Link text to page background is now only 4:1, which is not as good, though it still passes WCAG 2 Level AA under the "large text" exception, which states that if the text is large (which this qualifies as, due to being bold, on top of the larger base font size the site as a whole uses), then it's acceptable.
 * Link text to body text is now 3:1, which means more people are going to be able to differentiate between them.

I've been fiddling with the sliders for some time, but couldn't come up with a palette that felt the same as the original one that doesn't also have a slightly worse link text to background ratio.  In fact I am now somewhat inspired to write some code to exhaustively find the best such ratios between three colours, with artistic constraints, but that's probably not happening anytime soon...

Preserving the original character of the site was a priority and I hope you feel I've succeeded in doing this.  I'm still a little reticent due to the reduction in contrast between link text and page background (even though it's still considered acceptable under Level AA, it is worse than what was there originally) so might have another go with these sliders over the next few days again, to see if I can do any better.

A "wildcard" alternative approach, which could support even higher contrast throughout, would be to use a very different hue for the link colour, such as green (I think it looks quite cool, but imagine many may not!)

This PR also makes the following changes:

 * The new body text colour is used for headings too (so they match)
 * The new link text colour is used as the selection background colour (to simplify the palette)

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
Will give some more lengthy thoughts on this soon but CC @remiprev for thoughts on this; he came up with the original palette and has more aesthetic sense in his toe than I have in the rest of my body combined 😆

**Comment by remiprev** [comment]
@matatk Could you post a screenshot of the whole page _before_ and _after_ your code changes? I don’t mind improving the colors, I’d just like to compare the end result.

**Comment by MikeMcQuaid** [comment]
@matatk I'm afraid I merged https://github.com/Homebrew/homebrew.github.io/pull/166 which will cause a bunch of nasty merge conflicts such that it's maybe worth trying to remake this PR from scratch again. As a positive you should now only need to change colours in a single location.

**Comment by matatk** [comment]
@MikeMcQuaid I've been a bit laggy on this; no worries. Will have a look and possibly re-do. Nice to hear regarding the DRY on the CSS :-).

@remiprev sure; will send when I've updated/redone this to fit the new CSS.

I'm still somewhat torn by the fact that, in order to bring up the contrast between link and body text, I had to reduce the contrast of the body text (both are within acceptable levels for large fonts at WCAG level AA, though it feels like it shouldn't be a zero-sum game—though the only way to increase *both* would be to use a different accent/link colour for the site, which would change the appearance a lot). Anyway, more on that in a re-worked PR :-).

**Comment by MikeMcQuaid** [comment]
@matatk I can't remember if I mentioned this previous but another option for finding colours (and prompted the new colour scheme) are these new icons: 
https://avatars2.githubusercontent.com/u/1503512?v=3&s=400
https://avatars1.githubusercontent.com/u/1589480?v=3&s=400

**Comment by matatk** [comment]
@MikeMcQuaid: thanks for the pointers to the artwork. Sorry I have not yet done the other PR; it's a simple patch, but I have been super-busy; will be on it soon, though.

**Comment by matatk** [comment]
Have created #167 now, so will close this.

**Pull request closed without merging**
