### PR TITLE
Drop a reference to macOS 10.5, which isn't supported by homebrew

### PR DESCRIPTION
**Pull request by alex**

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
Thanks @alex!

**Comment by alex** [comment]
@MikeMcQuaid no problem! FYI, it looks like a few of the translated index.html's also have this reference.

**Comment by MikeMcQuaid** [comment]
@alex Would you mind removing it from them too? Feel free to say "no" and I'll take a look. Thanks again!

**Comment by alex** [comment]
@MikeMcQuaid #176, cheers

**Pull request merged**
