### PR TITLE
Added Swedish translation

### PR DESCRIPTION
**Pull request by WizuO**
Added Swedish translation strings to brew.sh website.

### CODE REVIEW

**Comment by mikemcquaid** [comment]
Thanks!

**Comment by WizuO** [comment]
No problem! Just heads up, the 'ä' character in one of the titles isn't bolded right now. Does it need any extra html tags? 
Link: http://brew.sh/index_se.html

**Comment by dunn** [comment]
My guess is that's a limitation of the webfont we're using.

**Comment by WizuO** [comment]
If needed I can just revert that specific title back to English, as I noticed the Norwegian translation has done. There is really no other way of writing it without using non-English characters.

**Comment by dunn** [comment]
I'd be open to switching to a new font, if we can find a similar free one with better character support.

**Comment by bjorno** [comment]
Yeah, that could be necessary. I just realized this issue has already been brought to attention, with no resolution: https://github.com/Homebrew/homebrew.github.io/issues/41

**Comment by dunn** [comment]
I'll open a PR soon to switch to this font https://www.google.com/fonts/specimen/Roboto+Slab unless we come across a better alternative.

**Comment by bjorno** [comment]
Looks like a good replacement. Thanks you!

**Pull request merged**
