### PR TITLE
Update github corner

### PR DESCRIPTION
**Pull request by vinkla**
Switched to the new better looking github corners http://tholman.com/github-corners/ I've added the red corner.

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
I prefer the old one, I think it's more obvious what it's doing if you don't recognise the :octocat:.

**Comment by vinkla** [comment]
Yeah, I agree the old one is more obvious. Though, IMO the new one looks so good.

**Comment by MikeMcQuaid** [comment]
I do quite like the new one but probably more for projects where the chances of people not knowing the :octocat: are 0️⃣. Let's leave this open for a bit and see what others think.

**Comment by vinkla** [comment]
Okay, sounds fare.

**Comment by UniqMartin** [comment]
I'm afraid I have to agree with Mike that I also prefer the old one. The new ones are minimalist and cute, but a lot less obvious. However, if we decided to pick one of the new ones, I think we should adjust the colors to match our color scheme.

**Comment by vinkla** [comment]
@UniqMartin which color do you prefer?

**Comment by UniqMartin** [comment]
I think the Octocat using the background color and the corner itself using the text color of the headings (like `h1` and `h2`).

**Comment by vinkla** [comment]
@UniqMartin sounds good. It is fairly easy to add custom colors. We can just update the hex value.

**Comment by MikeMcQuaid** [comment]
Passing, sorry!

**Comment by vinkla** [comment]
No worries!

**Pull request closed without merging**
