### PR TITLE
Better RTL support

### PR DESCRIPTION
**Pull request by sijad**

### CODE REVIEW

**Comment by sijad** [comment]
also it can be a good idea to remove `screen.rtl.css` and merge it with `screen.css`
please let me know

**Comment by mikemcquaid** [comment]
Yeh, a single stylesheet would be preferable, thanks!

**Comment by sijad** [comment]
@mikemcquaid thanks for review, additional css file has been merged
please review again
thanks again

**Comment by mikemcquaid** [comment]
Looks good, thanks!

**Pull request merged**
